# Generated by Django 5.0 on 2024-01-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("album_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to="Upload/"),
        ),
    ]
